Repository splunk-soar-connectors/smtp, pull requests merged in 2023-01, with the labels that each got.

#9 PAPP-28993: Do not require the username field
  release_notes/unreleased.md
  smtp.json
  smtp_connector.py
Labels: splunk-supported

#11 PSAAS-11501: bleach outgoing HTML email to prevent XSS
  smtp_connector.py
Labels: splunk-supported, external-contributor, PAPP-29025

#14 PAPP-28928 : SMTP : Bugfix : resolved lintng issues
  LICENSE
  release_notes/2.2.0.md
  release_notes/2.3.0.md
  release_notes/unreleased.md
  requirements.txt
  smtp.json
  smtp_connector.py
  wheels/shared/bleach_allowlist-1.0.3-py2.py3-none-any.whl
Labels: splunk-supported

#12 PSAAS-11501: pre-commit changes
  requirements.txt
  smtp.json
  wheels/py3/packaging-21.3-py3-none-any.whl
  wheels/py3/packaging-22.0-py3-none-any.whl
  wheels/py3/pyparsing-3.0.9-py3-none-any.whl
  wheels/shared/bleach-3.3.1-py2.py3-none-any.whl
  wheels/shared/six-1.16.0-py2.py3-none-any.whl
  wheels/shared/webencodings-0.5.1-py2.py3-none-any.whl
Labels: splunk-supported, external-contributor, PAPP-29027
